---
- name: install Apache packages
  apt_rpm: name={{ item }} state=installed update_cache=True
  with_items:
   - apache2-base
   - apache2-mod_php7
   - apache2-mod_ssl
  no_log: True

- name: check certificate file
  stat: path=/var/lib/ssl/certs/httpd2.cert
  register: apache_cert_file
  no_log: True

- name: generate certificate file
  shell: /usr/bin/httpd2-cert-sh generate httpd2
  when: apache_cert_file.stat.exists == False

- name: enable Apache2 module filter
  apache2_module: state=present name=filter

- name: enable Apache2 module ssl
  apache2_module: state=present name=ssl

- name: enable Apache2 module rewrite
  apache2_module: state=present name=rewrite

- name: enable Apache2 module headers
  apache2_module: state=present name=headers

- name: enable Apache2 module env
  apache2_module: state=present name=env

- name: enable Apache2 module dir
  apache2_module: state=present name=dir

- name: enable Apache2 module mime
  apache2_module: state=present name=mime

- name: enable HTTPS (default_https)
  command: a2ensite default_https
  register: cmd1_result
  no_log: True
  changed_when: cmd1_result.stdout != "Site config .confThis site is already enabled!"

- name: enable HTTPS (https)
  command: a2enport https
  register: cmd1_result
  no_log: True
  changed_when: cmd1_result.stdout != "Port config https.conf is already enabled!"

- name: configure port 80
  lineinfile:
    dest: /etc/httpd2/conf/sites-available/ports_all.conf
    regexp: '^NameVirtualHost *:80$'
    line: 'NameVirtualHost *:80'
    state: present
    insertafter: EOF

- name: configure port 443
  lineinfile:
    dest: /etc/httpd2/conf/sites-available/ports_all.conf
    regexp: '^NameVirtualHost *:443$'
    line: 'NameVirtualHost *:443'
    state: present
    insertafter: EOF

- name: change example server name
  replace:
    path: /etc/httpd2/conf/sites-available/default_https.conf
    regexp: 'www\.example\.com'
    replace: 'localhost.localdomain'

- name: change _default_ placeholder for https
  replace:
    path: /etc/httpd2/conf/sites-available/default_https.conf
    regexp: '_default_'
    replace: '*'

- name: set port 80 for default server
  lineinfile:
    dest: /etc/httpd2/conf/sites-available/default.conf
    regexp: '^<VirtualHost \*>'
    line: '<VirtualHost *:80>'

- name: add RewriteEngine On
  lineinfile:
    dest: /etc/httpd2/conf/sites-available/default.conf
    regexp: '^RewriteEngine On$'
    line: 'RewriteEngine On'
    state: present
    insertbefore: '^<\/VirtualHost>'

- name: add RewriteCond
  lineinfile:
    dest: /etc/httpd2/conf/sites-available/default.conf
    regexp: '^RewriteCond'
    line: 'RewriteCond %{HTTPS} !=on'
    state: present
    insertbefore: '^<\/VirtualHost>'

- name: add RewriteRule
  lineinfile:
    dest: /etc/httpd2/conf/sites-available/default.conf
    regexp: '^RewriteRule'
    line: 'RewriteRule ^/(.*) https://%{HTTP_HOST}/$1 [R,L]'
    state: present
    insertbefore: '^<\/VirtualHost>'

- name: detect PHP settings
  shell: rpm -ql apache2-mod_php7 | grep php.ini
  args:
    warn: no
  register: php_ini
  no_log: True
  changed_when: False

- name: configure PHP memory_limit setting
  ini_file:
    path: "{{ php_ini.stdout }}"
    section: PHP
    option: memory_limit
    value: "512M"
  no_log: True

- name: configure PHP upload_max_filesize setting
  ini_file:
    path: "{{ php_ini.stdout }}"
    section: PHP
    option: upload_max_filesize
    value: "32M"
  no_log: True

- name: reload Apache2 configuration
  command: service httpd2 condreload
  args:
    warn: no
  changed_when: False

- name: start Apache service
  service: name=httpd2 state=started enabled=yes

- name: detect HTTP DocumentRoot
  shell: "awk '/^[[:space:]]*DocumentRoot/ {print \"DocumentRoot for http: \" $2}' /etc/httpd2/conf/sites-enabled/000-default.conf"
  changed_when: False

- name: detect HTTPS DocumentRoot
  shell: "awk '/^[[:space:]]*DocumentRoot/ {print \"DocumentRoot for https: \" $2}' /etc/httpd2/conf/sites-enabled/000-default_https.conf"
  changed_when: False
