---
- name: install MariaDB server packages
  apt_rpm: name={{ item }} state=installed update_cache=True
  with_items:
   - mariadb-server

- name: start MariaDB service
  service:
    name: mysqld
    state: started
    enabled: yes
